name: Health check

on:
  workflow_dispatch:
  schedule:
    # 0 0 */3 * *  says at 00:00 (midnight) every three days.
    # https://stackoverflow.com/questions/4549542/cron-job-every-three-days/44930849
    - cron: 0 0 */3 * *

jobs:
  dryRun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn

      - name: Perform dry-run
        run: yarn dryRun
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY}}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET}}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY}}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET}}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY}}
          GOAL: ${{ secrets.GOAL}}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
